baseurl: ""

repo: "https://github.com/yao-consulent"
github_user: "yao-consulent"
github_repo: "yao-consulent.github.io"

collections:
  overYao:
    output: true
  samenwerkingen:
    output: true

  