backend:
    name: github
    api_root: https://api.github.com
    base_url: https://api.netlify.com
    repo: yao-consulent/yao-consulent.github.io
    branch: main
    site_domain: tender-mclean-687aff.netlify.com
    auth_endpoint: auth

media_folder: "images"

collections:
    - name: "basiskennis" # Used in routes, e.g.,/admin/collections/blog
      label: "Basiskennis" # Used in the UI
      folder: "_courses/basis/basiskennis/" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - { label: "title", name: "title", widget: "string" }
          - { label: "tags", name: "tags", widget: "list" }
          - { label: "definitions", name: "definitions", widget: "list" }
          - { label: "Body", name: "body", widget: "markdown" }