backend:
    name: github
    api_root: https://api.github.com
    base_url: https://api.netlify.com
    repo: yao-consulent/yao-consulent.github.io
    branch: main
    site_domain: tender-mclean-687aff.netlify.app
    auth_endpoint: auth

media_folder: "images"

collections:
    - name: "samenwerkingen" # Used in routes, e.g.,/admin/collections/blog
      label: "Samenwerkingen" # Used in the UI
      folder: "_samenwerkingen/" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - { label: "title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
    - name: "algemene pagina's"
      label: "algemene pagina's"
      files: 
        - name: "publicaties"
          label: "publicaties"
          file: "/publicaties.md"
          fields: # The fields for each document, usually in front matter
            - { label: "title", name: "title", widget: "string" }
            - { label: "Body", name: "body", widget: "markdown" }
        - name: "hoofdpagina"
          label: "hoofdpagina"
          file: "/index.md"
          fields: # The fields for each document, usually in front matter
            - { label: "title", name: "title", widget: "string" }
            - { label: "Body", name: "body", widget: "markdown" }
        - name: "contactpagina"
          label: "contactpagina"
          file: "/contact.md"
          fields: # The fields for each document, usually in front matter
            - { label: "title", name: "title", widget: "string" }
            - { label: "Body", name: "body", widget: "markdown" }